<a href="https://colab.research.google.com/github/galahadmq/HWforProjector/blob/main/%229_1_assignment_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [ ]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [3]:
import numpy as np
res = np.array([1, 2, 3, 4, 5])

print(res)

[1 2 3 4 5]


In [4]:
import numpy as np
res2 = np.arange(1, 6)

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [5]:
import numpy as np
res3 = np.random.randint(1, 101, size=(3, 5))

print(res3)

[[ 44  27  58  88   5]
 [ 96  26  66  34  18]
 [ 92  11 100  56  38]]


### Task 3

Print the first row of array `res3`.

In [8]:
import numpy as np
res3 = np.random.randint(1, 101, size=(3, 5))

print(res3)

[[35 68 55  1 10]
 [24 45 60 87 37]
 [15 83 24 69 21]]


### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [12]:
print(res3[:, :1])

[[35]
 [24]
 [15]]


### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [17]:
# Min
res_min = res3[0, 1]
for el in res3[:, 1]:
    if res_min > el:
        res_min = el

print('min =', res_min)

min = 45


In [19]:
# Max
res_max = res3[0, 1]
for el in res3[:, 1]:
    if res_max < el:
        res_max = el

print('max =', res_max)

max = 83


In [20]:
# Sum
res_sum = 0
res_max = res3[0, 1]
for el in res3[:, 1]:
    res_sum +=el

print('sum =', res_sum)

sum = 196


### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [21]:
import numpy as np

def f(x):
    return np.exp(2 * x)

x = np.arange(0, 1.1, 0.1)
f_x = f(x)
print(f_x)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [ ]:
df = pd.read_csv("https://web.stanford.edu/class/cs102/datasets/Titanic.csv")

### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [29]:
import pandas as pd
print(df.columns)

Index(['last', 'first', 'gender', 'age', 'class', 'fare', 'embarked',
       'survived'],
      dtype='object')


In [28]:
first_ten_rows = df.head(10)
print(first_ten_rows)

        last                                       first gender   age  class  \
0     Braund                             Mr. Owen Harris      M  22.0      3   
1    Cumings  Mrs. John Bradley (Florence Briggs Thayer)      F  38.0      1   
2  Heikkinen                                  Miss Laina      F  26.0      3   
3   Futrelle          Mrs. Jacques Heath (Lily May Peel)      F  35.0      1   
4      Allen                           Mr. William Henry      M  35.0      3   
5      Moran                                   Mr. James      M   NaN      3   
6   McCarthy                               Mr. Timothy J      M  54.0      1   
7    Palsson                        Master Gosta Leonard      M   2.0      3   
8    Johnson    Mrs. Oscar W (Elisabeth Vilhelmina Berg)      F  27.0      3   
9     Nasser                 Mrs. Nicholas (Adele Achem)      F  14.0      2   

      fare     embarked survived  
0   7.2500  Southampton       no  
1  71.2833    Cherbourg      yes  
2   7.9250  So

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [40]:
df['full_name'] = df['last'] + ' ' + df['first']
print(df.columns)

KeyError: 'last'

### Task 10

Remove the two original columns - last, first.

In [39]:
df = df.drop(['last', 'first'], axis=1)
print(df.columns)

Index(['gender', 'age', 'class', 'fare', 'embarked', 'survived', 'full_name'], dtype='object')


### Task 11

Calculate the total number of survivors in the dataset.

In [45]:
df['survived'] = df['survived'].map({'yes': 1, 'no': 0})

total_survivors = df['survived'].sum()
print(f"Total number of survivors: {total_survivors}")

Total number of survivors: 0.0
